INSERT INTO FOOD (FOOD_ID, FOOD_NAME, DESCRIPTION, PRICE) VALUES
(1, 'Butter Chicken', 'Tender chicken cooked in a creamy tomato-based gravy.', 350.00),
(2, 'Chicken Tikka Masala', 'Marinated chicken tikka in a spiced creamy sauce.', 380.00),
(3, 'Palak Paneer', 'Spinach and Indian cheese in a creamy gravy.', 320.00),
(4, 'Dal Makhani', 'Slow-cooked black lentils in a creamy sauce.', 280.00),
(5, 'Chole Bhature', 'Spiced chickpeas served with fried bread.', 250.00),
(6, 'Samosa', 'Deep-fried pastry filled with potatoes and peas.', 80.00),
(7, 'Vegetable Biryani', 'Aromatic rice dish with mixed vegetables.', 290.00),
(8, 'Chicken Biryani', 'Aromatic rice dish with chicken.', 340.00),
(9, 'Mutton Biryani', 'Aromatic rice dish with mutton.', 390.00),
(10, 'Paneer Tikka', 'Marinated and grilled Indian cheese.', 300.00),
(11, 'Aloo Gobi', 'Potatoes and cauliflower cooked with spices.', 240.00),
(12, 'Baingan Bharta', 'Mashed eggplant cooked with spices.', 260.00),
(13, 'Rogan Josh', 'Aromatic lamb curry from Kashmir.', 420.00),
(14, 'Malai Kofta', 'Deep-fried vegetable balls in a creamy sauce.', 330.00),
(15, 'Tandoori Chicken', 'Chicken marinated in yogurt and spices, cooked in a tandoor.', 370.00),
(16, 'Seekh Kebab', 'Minced meat skewers cooked in a tandoor.', 350.00),
(17, 'Naan', 'Leavened bread baked in a tandoor.', 60.00),
(18, 'Garlic Naan', 'Leavened bread baked in a tandoor with garlic.', 70.00),
(19, 'Roti', 'Unleavened flatbread.', 40.00),
(20, 'Plain Rice', 'Steamed white rice.', 120.00),
(21, 'Jeera Rice', 'Rice cooked with cumin seeds.', 150.00),
(22, 'Raita', 'Yogurt with vegetables or spices.', 80.00),
(23, 'Gulab Jamun', 'Deep-fried milk balls in sugar syrup.', 100.00),
(24, 'Rasgulla', 'Cheese balls in sugar syrup.', 90.00),
(25, 'Lassi', 'Yogurt-based drink.', 120.00),
(26, 'Mango Lassi', 'Yogurt-based drink with mango.', 150.00),
(27, 'Masala Dosa', 'Crispy crepe filled with spiced potatoes.', 220.00),
(28, 'Idli Sambar', 'Steamed rice cakes served with lentil soup.', 180.00),
(29, 'Vada Sambar', 'Fried lentil donuts served with lentil soup.', 200.00),
(30, 'Uttapam', 'Thick pancake made from rice and lentil batter.', 210.00),
(31, 'Upma', 'Semolina dish cooked with vegetables.', 160.00),
(32, 'Poha', 'Flattened rice cooked with spices.', 150.00),
(33, 'Aloo Tikki', 'Potato patties served with chutney.', 90.00),
(34, 'Pani Puri', 'Hollow crispy spheres filled with spiced water and potatoes.', 100.00),
(35, 'Bhel Puri', 'Puffed rice snack with vegetables and chutney.', 120.00),
(36, 'Dahi Puri', 'Puffed rice snack with yogurt and chutney.', 130.00),
(37, 'Pav Bhaji', 'Vegetable curry served with bread rolls.', 240.00),
(38, 'Vada Pav', 'Potato fritter in a bread roll.', 90.00),
(39, 'Misal Pav', 'Spicy lentil curry served with bread rolls.', 230.00),
(40, 'Kulfi', 'Indian ice cream.', 110.00),
(41, 'Falooda', 'Dessert drink with vermicelli, rose syrup, and ice cream.', 160.00),
(42, 'Jalebi', 'Deep-fried batter swirls in sugar syrup.', 80.00),
(43, 'Gajar Halwa', 'Carrot pudding.', 120.00),
(44, 'Moong Dal Halwa', 'Lentil pudding.', 130.00),
(45, 'Rasmalai', 'Cheese patties in thickened milk.', 110.00),
(46, 'Shahi Tukda', 'Bread pudding.', 140.00),
(47, 'Kheer', 'Rice pudding.', 100.00),
(48, 'Butter Naan', 'Leavened bread baked in a tandoor with butter.', 80.00),
(49, 'Paneer Butter Masala', 'Paneer cooked in a creamy tomato-based gravy with butter.', 360.00),
(50, 'Kadai Paneer', 'Paneer cooked in a wok with bell peppers and spices.', 340.00),
(51, 'Mushroom Masala', 'Mushroom cooked in a spiced gravy.', 300.00),
(52, 'Bhindi Masala', 'Okra cooked with spices.', 250.00),
(53, 'Dal Tadka', 'Lentils tempered with spices.', 260.00),
(54, 'Chicken Curry', 'Traditional chicken curry.', 360.00),
(55, 'Mutton Curry', 'Traditional mutton curry.', 410.00),
(56, 'Fish Curry', 'Fish cooked in a spiced gravy.', 380.00),
(57, 'Egg Curry', 'Eggs cooked in a spiced gravy.', 280.00),
(58, 'Chana Masala', 'Chickpeas cooked in a spiced gravy.', 240.00),
(59, 'Rajma', 'Kidney beans cooked in a spiced gravy.', 250.00),
(60, 'Kofta Curry', 'Vegetable balls in a spiced gravy.', 320.00),
(61, 'Malai Kofta Curry', 'Creamy vegetable balls in a rich gravy.', 350.00),
(62, 'Veg Manchurian', 'Indo-Chinese vegetable balls in a sauce.', 280.00),
(63, 'Gobi Manchurian', 'Indo-Chinese cauliflower in a sauce.', 270.00),
(64, 'Chilli Paneer', 'Indo-Chinese paneer in a spicy sauce.', 320.00),
(65, 'Hakka Noodles', 'Indo-Chinese noodles with vegetables.', 250.00),
(66, 'Schezwan Noodles', 'Indo-Chinese noodles with a spicy Schezwan sauce.', 270.00),
(67, 'Fried Rice', 'Indo-Chinese fried rice with vegetables.', 240.00),
(68, 'Schezwan Fried Rice', 'Indo-Chinese fried rice with a spicy Schezwan sauce.', 260.00),
(69, 'Spring Roll', 'Deep-fried vegetable rolls.', 150.00),
(70, 'Momos', 'Steamed dumplings with vegetable or meat filling.', 200.00),
(71, 'Thukpa', 'Noodle soup with vegetables or meat.', 280.00),
(72, 'Chowmein', 'Stir-fried noodles with vegetables.', 240.00),
(73, 'Manchow Soup', 'Spicy and tangy Indo-Chinese soup.', 180.00),
(74, 'Hot and Sour Soup', 'Indo-Chinese soup with a hot and sour flavor.', 190.00),
(75, 'Sweet Corn Soup', 'Creamy Indo-Chinese soup with sweet corn.', 170.00),
(76, 'Lemon Coriander Soup', 'Soup flavored with lemon and coriander.', 160.00),
(77, 'Hara Bhara Kabab', 'Vegetable patties made from spinach and green peas.', 280.00),
(78, 'Dahi Ke Kebab', 'Yogurt and cheese patties.', 290.00),
(79, 'Tandoori Aloo', 'Potatoes marinated in tandoori spices and cooked in a tandoor.', 270.00),
(80, 'Paneer Lababdar', 'Paneer in a rich and creamy tomato gravy.', 370.00),
(81, 'Methi Chaman', 'Paneer cooked with fenugreek leaves.', 350.00),
(82, 'Kashmiri Dum Aloo', 'Potatoes cooked in a Kashmiri-style gravy.', 290.00),
(83, 'Navratan Korma', 'Vegetable curry with nine different gems.', 340.00),
(84, 'Shahi Paneer', 'Paneer in a rich and creamy cashew-based gravy.', 380.00),
(85, 'Dum Aloo', 'Potatoes cooked in a thick gravy.', 280.00),
(86, 'Punjabi Thali (Veg)', 'Assorted vegetarian dishes served with rice, bread, and dessert.', 450.00),
(87, 'Punjabi Thali (Non-Veg)', 'Assorted non-vegetarian dishes served with rice, bread, and dessert.', 550.00),
(88, 'Gujarati Thali', 'Assorted Gujarati dishes served with rice, bread, and dessert.', 420.00),
(89, 'South Indian Thali', 'Assorted South Indian dishes served with rice, sambar, and rasam.', 400.00),
(90, 'Dosa', 'Crispy crepe made from rice and lentil batter.', 200.00),
(91, 'Mysore Masala Dosa', 'Dosa with spicy chutney spread.', 240.00),
(92, 'Rava Dosa', 'Dosa made from semolina batter.', 220.00),
(93, 'Onion Uttapam', 'Uttapam with onions.', 230.00),
(94, 'Coconut Chutney', 'Chutney made from coconut.', 60.00),
(95, 'Sambar', 'Lentil-based vegetable stew.', 80.00),
(96, 'Rasam', 'South Indian soup made with tamarind and spices.', 70.00),
(97, 'Filter Coffee', 'South Indian coffee.', 80.00),
(98, 'Masala Chai', 'Spiced Indian tea.', 60.00),
(99, 'Badam Milk', 'Almond milk.', 100.00),
(100, 'Jeera Soda', 'Soda with cumin flavor.', 70.00);