services:
  restaurant-db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    healthcheck:
      #      `pg_isready` is a utility provided with PostgreSQL to check the connection status of a PostgreSQL server.
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m