CREATE TABLE FOOD (
    FOOD_ID INT PRIMARY KEY,
    FOOD_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(6, 2) NOT NULL
);

CREATE TABLE TAG (
    TAG_ID INT PRIMARY KEY,
    TAG_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE FOOD_TAG (
    FOOD_ID INT,
    TAG_ID INT
);